#!/bin/sh

##
# This script will enter modules/ and run every script there with:
# 'fetch', 'unpack', and 'build' successively
#
# If a module needs to do the install to STAGEDIR itself, that should be done
# inside of make_new_initrd in the TOPDIR
#

while getopts c: name
do
  case ${name} in
  c)  CONFIGOPTIONS=$OPTARG
      printf 'Global configure options set to %s' ${CONFIGOPTIONS};;
  ?)  printf "Usage: %s: [-i] initrd_version kernel_version" $0
      exit 1;;
  esac
done
shift $(($OPTIND -1))

##
# FETCH
#

for file in modules/*; do
  ${file} fetch
done

##
# UNPACK
#

for file in modules/*; do
  ${file} unpack
done

##
# BUILD
#

for file in modules/*; do
  ${file} build ${CONFIGOPTS}
done


