#!/bin/ash

. /etc/library.sh

header "${PRODUCT_NAME} ${PRODUCT_VER} startup"

msg -n "Mounting /proc filesystem"
mount -t proc none /proc > /dev/null 2>&1
if [ "$?" = "0" ];
then
	ok_msg
else
	fatal_error "Unable to mount /proc can't continue"
fi

msg -n "Mounting /sys filesystem"
mount -t sysfs none /sys > /dev/null 2>&1
if [ "$?" = "0" ];
then
	ok_msg
else
	fatal_error "Unable to mount /sys can't continue"
fi

msg -n "Mounting tmpfs on /dev for udev"
mount -n -t tmpfs none /dev > /dev/null 2>&1
if [ "$?" = "0" ];
then
	ok_msg
else
	fatal_error "Unable to mount /dev can't continue"
fi

msg -n "Setting udev as hotplug agent and triggering events"
#echo "/usr/local/sbin/udev" > /proc/sys/kernel/hotplug
/usr/local/sbin/udevd --daemon
/usr/local/bin/udevtrigger
ok_msg

msg -n "brining up the loopback interface"
/sbin/ifconfig lo 127.0.0.1 netmask 255.0.0.0 up > /dev/null 2>&1
ok_or_fail $?

for i in `cat /proc/cmdline`
do
	case ${i}
	in
		syslog=*)
			RSYSLOG=`echo ${i} | sed 's/syslog=//'`
		;;
	esac
done

msg -n "Starting the syslog daemon"
if [ "${SYSLOG}" != "" ]
then
	/sbin/syslogd -m 0 -L -R ${RSYSLOG} > /dev/null 2>&1
else
	/sbin/syslogd -m 0 > /dev/null 2>&1
fi
ok_or_fail $?

msg -n "Starting the kernel log daemon"
/sbin/klogd -c 1 > /dev/null 2>&1
ok_or_fail $?

msg -n "Disabling console blanking"
echo -en "\033[9;0]"
ok_msg

export PATH=$PATH:/usr/local/bin

