#!/bin/sh -e

# This script is run if an optical drive lacks a rule for persistent naming.
#
# It adds symlinks for optical drives based on the device class determined
# by cdrom_id and used ID_PATH to identify the device.
#
# (C) 2006 Marco d'Itri <md@Linux.IT>
# (C) 2008 Advanced Clustering Technologies, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation version 2 of the License.
#
# Don't blame Marco for our lameness--if you think this is lame, anyway...

find_next_available() {
    local links="$1"

    local basename=${links%%[ 0-9]*}
    local max=-1
    for name in $links; do
        local num=${name#$basename}
        [ "$num" ] || num=0
        [ $num -gt $max ] && max=$num
    done

    local max=$(($max + 1))
    # "name0" actually is just "name"
    [ $max -eq 0 ] && return
    echo "$max"
}

link_num=$(find_next_available "/dev/cdrom*")
link="cdrom$link_num"

echo $link

exit 0

