
name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone breakin
        uses: actions/checkout@v3
        with:
          repository: reperio/breakin
          path: breakin
      - name: Setup Alpine
        id:   alpine
        uses: jirutka/setup-alpine@v1.1.1
        with:
          packages: >
            linux-lts
            linux-headers
            alpine-sdk
            dropbear-ssh
            util-linux-misc
            mkinitfs
            curl-dev
            ncurses-dev
            openmpi-dev
            openblas-dev
            rasdaemon
      - name: Build breakin
        run: |
          cd breakin
          cat ../mce.sh > scripts/tests/mcelog
          chmod 0750 scripts/tests/mcelog
          sed -i -e '4irm -f /tmp/.syslog_pos' scripts/stop.sh
          if [ $(find /usr/lib -name libtinfo.so* 2>/dev/null | wc -l) -eq 0 ]
          then
            sed -i -e s/-ltinfo//g Makefile
          fi
          make
        shell: alpine.sh {0}
      - name: Install breakin
        run: make install
        shell: alpine.sh -r {0}
      - name: Make initramfs
        run: |
          apk info -L ncurses-libs libcurl brotli-libs nghttp2-libs \
          libssl zlib openmpi openblas ipmitool readline rasdaemon \
          dmidecode sqlite-libs libsmartcols dropbear-ssh | \
          grep -v 'contains:' | grep . >> breakin.files
          mkinitfs -P $(pwd) -c mkinitfs.conf -i init -o /initramfs $(ls -la /lib/modules | tail -1 | awk '{print $NF}')
        shell: alpine.sh -r {0}
      - name: Copy Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sudo mv ${{ steps.alpine.outputs.root-path }}/boot/vmlinuz-lts vmlinux
          sudo mv ${{ steps.alpine.outputs.root-path }}/initramfs .
          sudo chmod 0644 vmlinux initramfs
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vmlinux
            initramfs

